<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="2.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
    xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
    xmlns:video="http://www.google.com/schemas/sitemap-video/1.1"
    xmlns:xhtml="http://www.w3.org/1999/xhtml">

	<xsl:output method="html" indent="yes" encoding="UTF-8"/>

	<xsl:template match="/">
		<html>
			<head>
				<title>XML Sitemap</title>
				<style>
					body {
					font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
					color: #444;
					max-width: 1200px;
					margin: 0 auto;
					padding: 20px;
					}
					.header {
					padding: 20px 0;
					border-bottom: 1px solid #eee;
					}
					.header p {
					color: #666;
					}
					table {
					width: 100%;
					border-collapse: collapse;
					margin-top: 20px;
					}
					th {
					background-color: #f8f9fa;
					text-align: left;
					padding: 15px;
					font-size: 14px;
					font-weight: 600;
					color: #1a73e8;
					}
					td {
					padding: 12px 15px;
					border-bottom: 1px solid #eee;
					font-size: 14px;
					}
					tr:hover td {
					background-color: #f8f9fa;
					}
					a {
					color: #1a73e8;
					text-decoration: none;
					}
					a:hover {
					text-decoration: underline;
					}
					.priority, .changefreq {
					text-align: center;
					}
				</style>
			</head>
			<body>
				<div class="header">
					<h1>XML Sitemap</h1>
					<p>Generated by Ice Cream - This is an XML sitemap, meant for consumption by search engines.</p>
					<p>
						Learn more about <a href="http://sitemaps.org">XML sitemaps</a>.
					</p>
				</div>

				<table>
					<thead>
						<tr>
							<th>URL</th>
							<th>Last Modified</th>
							<th>Change Frequency</th>
							<th>Priority</th>
						</tr>
					</thead>
					<tbody>
						<xsl:for-each select="sitemap:urlset/sitemap:url">
							<tr>
								<td>
									<a href="{sitemap:loc}">
										<xsl:value-of select="sitemap:loc"/>
									</a>
								</td>
								<td>
									<xsl:value-of select="sitemap:lastmod"/>
								</td>
								<td class="changefreq">
									<xsl:value-of select="sitemap:changefreq"/>
								</td>
								<td class="priority">
									<xsl:value-of select="sitemap:priority"/>
								</td>
							</tr>
						</xsl:for-each>
					</tbody>
				</table>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>